# Training file folder
dir_train: ../dataset/layer_model/train/

# Warmup phase
level_warmup: [0.01, 0.08]
# IDR phase
level_idr: [0.01, 0.08]

# Training mode
train_mode: SSL

# Training setting
in_channels: 1
out_channels: 1
total_epoch: 180
warmup_epoch: 50
batch_size: 32
num_workers: 1
lr: !!float 2e-4
loss_type: l1         # option: l1 and l2
optimizer: AdamW      # option: AdamW and Adam
wd: 0
schedule: multistep   # option: cosine and multistep
milestones: [200]
gamma: 0.8
print_freq: 100       # iterations
save_state_freq: 5    # epoch
epsilon: 1

# Testing file folder
dir_test: ../dataset/layer_model/test/

# Test setting
cp_list: [50, 75, 100, 125, 150, 170]  # select trained model in which epoch

